[theme]
base = "dark"
primaryColor = "#10b981"
backgroundColor = "#0e131f"
secondaryBackgroundColor = "#182234"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = false
enableCORS = false
enableXsrfProtection = true
